spring.datasource.url=jdbc:postgresql://localhost:5432/leapkart-stg?createTableIfNotExists=true
spring.datasource.username=postgres
spring.datasource.password=sevi
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver